FROM registry.access.redhat.com/ubi9/ubi:latest AS production

ENV AAP_GATEWAY_URL=${AAP_GATEWAY_URL}
ENV OPENAPI_SPEC_URL="file:///var/www/aap-gateway-api.yaml"
ENV HOST=${HOST}
ENV PORT=${PORT}
ENV PYTHONUNBUFFERED=1
ENV DEBUG=True

# Install dependencies
RUN dnf install -y \
    python3.12 \
    python3.12-pip

USER 1000
WORKDIR /var/www/

COPY ansible_mcp_tools/ ./ansible_mcp_tools/
COPY aap_gateway_api_2_5/server.py ./
COPY aap_gateway_api_2_5/aap-gateway-api.yaml ./
COPY aap_gateway_api_2_5/pyproject.toml ./pyproject.toml

# Compile application
RUN /usr/bin/python3.12 -m venv /var/www/venv
ENV PATH="/var/www/venv/bin:${PATH}"

RUN python3.12 -m pip install --no-cache-dir --no-binary=all .

# Launch!
ENTRYPOINT ["python3.12", "server.py"]

EXPOSE ${PORT}
