name: Build and Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The Ansible MCP Servers version to build and push"
        required: true
        default: "0.0.1"

jobs:

  build_push:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_MCP_VERSION: ${{ github.event.inputs.version }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/heads/main

      - name: Ansible Gateway MCP Server build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: aap_gateway_api_2_5/Containerfile
          tags: quay.io/ansible/ansible-mcp-gateway:${{ env.ANSIBLE_MCP_VERSION }}

      - name: Ansible Controller MCP Server build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: aap_controller_api_2_5/Containerfile
          tags: quay.io/ansible/ansible-mcp-controller:${{ env.ANSIBLE_MCP_VERSION }}
